[build]
  base = "."
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps" 